# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Edgee MCP Server

FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies (ignores potentially problematic prepare scripts)
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Runtime image
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy built files and dependencies from builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

# Default command
ENTRYPOINT ["node", "dist/index.js"]
