name: Publish mcp-server-edgee to npmjs
on:
  release:
    types:
      - released
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Compile and Build
        run: npm run build

      # Setup .npmrc file to publish to npm
      - name: Setup the node
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.14'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish mcp-server-edgee on npm
        run: npm publish --access public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
