name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint --fix=false

  Building:
    name: Compile source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Typecheck And Build Code
        run: npm run typecheck && npm run build-lib
